{
  "displayName": "Java with Tomcat",
  "description": "Java stack with OpenJDK and Tomcat 9.x",
  "tags": [
    "Java",
    "OpenJDK",
    "Tomcat"
  ],
  "links": {
    "self": "https://raw.githubusercontent.com/ldepandis/tomcat-codeready/main/latest.meta.yaml"
  }
}
